### ISSUE TITLE
Why does this codebase look similar to Atticmedia/Anvard?

### ISSUE THREAD

**Issue by domtancredi** [FrozenNode/Social#4]
https://bitbucket.org/atticmedia/anvard/

**Comment by janhartigan** [comment]
Because it's basically a straight lift with a few modifications to make it barely work.

**Comment by domtancredi** [comment]
Rock on. I've just gotten a stable version of it working with iOS // reverse auth (will probably make a blog post). Would be great to use your package instead, as I'm using your administrator package as well! 

Great work on the administrator package!
