### ISSUE TITLE
Any life in this package?

### ISSUE THREAD

**Issue by codivist** [FrozenNode/Social#8]
I am currenlty developing a site that is going to need oAuth client connections here shortly. I have been looking at a few others and most of them haven't been updated in over a year, and this 2 years.

FrozenNode, I've used your stuff often and have been well pleased with the stuff you guys make. Just hoping there is life in this project.  Is there?

**Comment by janhartigan** [comment]
@codivist unfortunately the major problem with this package is that it relies on HybridAuth, which is a disaster for various reasons. I originally ported this code over from anvard, which was its own giant disaster.

The good news is that you now can do this fairly easily in Laravel 5. Give this a look: http://laravel.com/docs/5.0/authentication#social-authentication
